server:
 # port: 9001
  servlet:
    context-path: /api/v1/employee
  

 
  #for liquibase
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/master.xml
#for database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservice_pms1
    username: postgres
    password: Jost@soft321
  application:
    name: employee-microservice
  jpa:
    hibernate:
      ddl-auto: none


eureka:
  instance:
    hostname: localhost




      
